package com.udacity.project4.utils

const val ACTION_GEOFENCE_EVENT = "ACTION_GEOFENCE_EVENT"
const val GEOFENCE_RADIUS = 20F
const val GEOFENCE_CHANNEL_ID = "GEOFENCE_CHANNEL_ID"


const val NOTIFICATION_ID = 1
const val GEOFENCE_PENDING_INTENT_REQUEST_CODE = 200
const val REMINDER_NOTIFICATION_PENDING_INTENT_REQUEST_CODE = 100
const val REMINDER_ID = "REMINDER_ID"

const val REQUEST_TURN_DEVICE_LOCATION_ON = 300